ALTER TABLE "TaxiDetail" ADD COLUMN "pickupLat" DOUBLE PRECISION;
ALTER TABLE "TaxiDetail" ADD COLUMN "pickupLng" DOUBLE PRECISION;
ALTER TABLE "TaxiDetail" ADD COLUMN "pickupAddress" TEXT;
ALTER TABLE "TaxiDetail" ADD COLUMN "dropoffLat" DOUBLE PRECISION;
ALTER TABLE "TaxiDetail" ADD COLUMN "dropoffLng" DOUBLE PRECISION;
ALTER TABLE "TaxiDetail" ADD COLUMN "dropoffAddress" TEXT;
